export const productSeeds = [
  {
    id: '1',
    _id: '1',
    name: 'iPhone 15 Pro Max',
    description: "Apple's latest flagship smartphone.",
    price: 1099,
    category: 'electronics',
    image: 'https://cdn.tgdd.vn/Products/Images/42/305658/iphone-15-pro-max-blue-thumbnew-600x600.jpg',
    brand: 'Apple',
    stock: 100,
    rating: 4.9
  },
  {
    id: '2',
    _id: '2',
    name: 'MacBook Air M2',
    description: 'Powerful and lightweight laptop from Apple.',
    price: 1199,
    category: 'computers',
    image: 'https://cdn8.web4s.vn/media/products/mac-air-m2/macbookairm2-midnight%201.jpg',
    brand: 'Apple',
    stock: 50,
    rating: 4.8
  },
  {
    id: '3',
    _id: '3',
    name: 'MacBook Pro 14" M2 Pro',
    description: 'High-performance laptop with M2 Pro chip.',
    price: 1999,
    category: 'computers',
    image: 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/refurb-mbp14-m2-silver-202303?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=ZmdRZFZQaThmdmpsRzMrNlU0TnIrNVN1UEFsa2dENVBwbUVOOUlVZ3dMdmRxTENLaEJiU0o5a1FqaDFsUHhYNjE1UUxLT2t0cW42N3FvQzVqaGhrVVltRElNTjY0QXJtekNDMXFQT2xOSU4rYWpGdS9XeFgvbS9ITnNYOEhYaG4',
    brand: 'Apple',
    stock: 30,
    rating: 4.9
  },
  {
    id: '4',
    _id: '4',
    name: 'Sony WH-1000XM5',
    description: 'Industry-leading noise-canceling headphones.',
    price: 399,
    category: 'audio',
    image: 'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Entertainment/Headphones%20and%20Earphones/Images/272419_jqvb9x.png?tr=w-600',
    brand: 'Sony',
    stock: 200,
    rating: 4.7
  },
  {
    id: '5',
    _id: '5',
    name: 'Samsung 65" QLED TV',
    description: 'Immersive 4K TV experience with QLED technology.',
    price: 1499,
    category: 'electronics',
    image: 'https://cdn.mediamart.vn/images/product/qled-tivi-4k-samsung-65-inch-65q80c-smart-tv_5304e716.png',
    brand: 'Samsung',
    stock: 10,
    rating: 4.6
  },
  {
    id: '6',
    _id: '6',
    name: 'Canon EOS R5',
    description: 'High-performance mirrorless camera from Canon.',
    price: 3799,
    category: 'cameras',
    image: 'https://i1.adis.ws/i/canon/eos-r5_front_rf24-105mmf4lisusm_square_32c26ad194234d42b3cd9e582a21c99b',
    brand: 'Canon',
    stock: 5,
    rating: 4.9
  },
  {
    id: '7',
    _id: '7',
    name: 'Apple Watch Series 9',
    description: 'Stay connected and healthy with the latest Apple Watch.',
    price: 399,
    category: 'electronics',
    image: 'https://akbroshop.com/wp-content/uploads/2022/08/hinh-aw-s7-xanh.jpg',
    brand: 'Apple',
    stock: 100,
    rating: 4.8
  },
  {
    id: '8',
    _id: '8',
    name: 'Dell XPS 15',
    description: 'Powerful laptop with stunning 4K display.',
    price: 1799,
    category: 'computers',
    image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9530/media-gallery/touch-black/notebook-xps-15-9530-t-black-gallery-1.psd?fmt=pjpg&wid=800',
    brand: 'Dell',
    stock: 20,
    rating: 4.7
  },
  {
    id: '9',
    _id: '9',
    name: 'Samsung Galaxy Tab S9 Ultra',
    description: 'Premium Android tablet with stunning AMOLED display.',
    price: 849,
    category: 'electronics',
    image: 'https://hanoicomputercdn.com/media/product/60370_may_tinh_bang_samsung_galaxy_tab_s7_plus_128gb_den.png',
    brand: 'Samsung',
    stock: 30,
    rating: 4.8
  },
  {
    id: '10',
    _id: '10',
    name: 'Sony A7 IV',
    description: 'Full-frame mirrorless camera with 33MP sensor.',
    price: 2499,
    category: 'cameras',
    image: 'https://zshop.vn/images/detailed/92/1634812545_1667800.jpg',
    brand: 'Sony',
    stock: 10,
    rating: 4.9
  },
  { 
    id: '11',
    _id: '11', 
    name: 'ROG Zephyrus G14', 
    description: 'Ultimate 14-inch gaming laptop.', 
    price: 1599, 
    category: 'computers', 
    image: 'https://www.primeabgb.com/wp-content/uploads/2025/08/ASUS-ROG-Zephyrus-G14-14-inch-AMD-Ryzen-AI-9-HX-370-RTX-5070-Ti-GPU-32GB-RAM-2TB-SSD-Gaming-Laptop-GA403WR-QS123WS.jpg', 
    brand: 'ASUS', 
    stock: 25, 
    rating: 4.8 
  },
  {
    id: '12',
    _id: '12',
    name: 'Logitech MX Master 3S',
    description: 'Performance wireless ergonomic mouse.',
    price: 99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800',
    brand: 'Logitech',
    stock: 150,
    rating: 4.9
  },
  {
    id: '13',
    _id: '13',
    name: 'Keychron Q1 Pro',
    description: 'Wireless custom mechanical keyboard.',
    price: 199,
    category: 'electronics',
    image: 'https://mechanicalkeyboards.com/cdn/shop/files/17105-KSGNZ-Keychron-Q1-Pro-w-Knob-Shell-White-Aluminum-75-Hotswap-Bluet.jpg?v=1766520376&width=750',
    brand: 'Keychron',
    stock: 45,
    rating: 4.8
  },
  {
    id: '14',
    _id: '14',
    name: 'AirPods Pro 2',
    description: 'MagSafe charging, active noise cancellation.',
    price: 249,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/51emillNpWL._AC_UF350,350_QL80_.jpg',
    brand: 'Apple',
    stock: 300,
    rating: 4.9
  },
  {
    id: '15',
    _id: '15',
    name: 'Nintendo Switch OLED',
    description: 'Vibrant 7-inch OLED screen.',
    price: 349,
    category: 'electronics',
    image: 'https://i.etsystatic.com/22580149/r/il/db60d8/3602821419/il_fullxfull.3602821419_303e.jpg',
    brand: 'Nintendo',
    stock: 80,
    rating: 4.7
  },
  {
    id: '16',
    _id: '16',
    name: 'GoPro HERO 12 Black',
    description: '5.3K video, hyper-smooth stabilization.',
    price: 399,
    category: 'cameras',
    image: 'https://m.media-amazon.com/images/I/61dUvabnSmL.jpg',
    brand: 'GoPro',
    stock: 60,
    rating: 4.6
  },
  {
    id: '17',
    _id: '17',
    name: 'DJI Mini 3 Pro',
    description: 'Lightweight drone with 4K HDR video.',
    price: 759,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/51wt4-myDiL.jpg',
    brand: 'DJI',
    stock: 15,
    rating: 4.8
  },
  {
    id: '18',
    _id: '18',
    name: 'Fitbit Charge 6',
    description: 'Advanced fitness and health tracker.',
    price: 159,
    category: 'fitness',
    image: 'https://m.media-amazon.com/images/I/41M+F43gRJL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Fitbit',
    stock: 200,
    rating: 4.5
  },
  {
    id: '19',
    _id: '19',
    name: 'Philips Hue Starter Kit',
    description: 'Smart lighting for your home.',
    price: 199,
    category: 'smarthome',
    image: 'https://m.media-amazon.com/images/I/51u3-6AeGiL.jpg',
    brand: 'Philips',
    stock: 100,
    rating: 4.7
  },
  {
    id: '20',
    _id: '20',
    name: 'Sonos One (Gen 2)',
    description: 'Powerful smart speaker with voice control.',
    price: 219,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/61JLYbKHBOL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Sonos',
    stock: 90,
    rating: 4.8
  },
  {
    id: '21',
    _id: '21',
    name: 'Kindle Paperwhite',
    description: '6.8" display, adjustable warm light.',
    price: 139,
    category: 'electronics',
    image: 'https://helios-i.mashable.com/imagery/comparisons/04xWc3e8dygWqXf9BjO7CYJ-item1.fit_lim.size_640x358.v1760549907.jpg',
    brand: 'Amazon',
    stock: 120,
    rating: 4.9
  },
  {
    id: '22',
    _id: '22',
    name: 'Steam Deck (512GB)',
    description: 'The most powerful gaming handheld.',
    price: 649,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/51N0jRIIopL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Valve',
    stock: 10,
    rating: 4.8
  },
  {
    id: '23',
    _id: '23',
    name: 'Bose QuietComfort Ultra',
    description: 'Personalized noise cancellation.',
    price: 429,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/51yWZxN3vRL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Bose',
    stock: 55,
    rating: 4.7
  },
  {
    id: '24',
    _id: '24',
    name: 'Surface Laptop 5',
    description: 'Sleek, powerful Windows laptop.',
    price: 1299,
    category: 'computers',
    image: 'https://images-cdn.ubuy.co.in/66218730e5044a1be3051cf8-microsoft-surface-laptop-5-15-intel-core.jpg',
    brand: 'Microsoft',
    stock: 40,
    rating: 4.6
  },
  {
    id: '25',
    _id: '25',
    name: 'WD Black SN850X 2TB',
    description: 'Top-tier NVMe SSD for gaming.',
    price: 189,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/61jQCrK6mFL._AC_UF1000,1000_QL80_.jpg',
    brand: 'WD',
    stock: 200,
    rating: 4.9
  },
  {
    id: '26',
    _id: '26',
    name: 'Corsair Vengeance 32GB RAM',
    description: 'DDR5 high-performance memory.',
    price: 119,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/61D2DDpDITL.jpg',
    brand: 'Corsair',
    stock: 180,
    rating: 4.8
  },
  {
    id: '27',
    _id: '27',
    name: 'Razer DeathAdder V3 Pro',
    description: 'Ultra-lightweight wireless mouse.',
    price: 149,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/51HNNPbYdML.jpg',
    brand: 'Razer',
    stock: 75,
    rating: 4.7
  },
  {
    id: '28',
    _id: '28',
    name: 'Samsung T7 Shield 2TB',
    description: 'Rugged portable SSD.',
    price: 229,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/71sKzf5EoyL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Samsung',
    stock: 110,
    rating: 4.9
  },
  {
    id: '29',
    _id: '29',
    name: 'Beats Studio Pro',
    description: 'Premium over-ear headphones.',
    price: 349,
    category: 'audio',
    image: 'https://accessworld.in/cdn/shop/files/beats-studio-pro-sandstone-1.jpg?v=1693399859&width=1000',
    brand: 'Beats',
    stock: 65,
    rating: 4.5
  },
  {
    id: '30',
    _id: '30',
    name: 'Google Pixel 8 Pro',
    description: 'AI-powered Google smartphone.',
    price: 999,
    category: 'electronics',
    image: 'https://in.static.webuy.com/product_images/Phones/Phones%20Android/SGOOPIX8P256GBUNLB_l.jpg',
    brand: 'Google',
    stock: 95,
    rating: 4.7
  },
  {
    id: '31',
    _id: '31',
    name: 'Nest Learning Thermostat',
    description: 'Smart temperature control.',
    price: 249,
    category: 'smarthome',
    image: 'https://i5.walmartimages.com/asr/ee4d0bec-0d2b-4c8a-8425-892bf305f42e_1.c5698b9408b60133ce62a2083cd1ff99.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
    brand: 'Google',
    stock: 50,
    rating: 4.8
  },
  {
    id: '32',
    _id: '32',
    name: 'Ring Video Doorbell 4',
    description: 'Enhanced wifi video doorbell.',
    price: 159,
    category: 'smarthome',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVIbUeSCKT99lNffbkptu1bkU3257KolDrJg&s',
    brand: 'Ring',
    stock: 130,
    rating: 4.6
  },
  {
    id: '33',
    _id: '33',
    name: 'Insta360 X3',
    description: 'Ultimate 360-degree action cam.',
    price: 449,
    category: 'cameras',
    image: 'https://m.media-amazon.com/images/I/61JIsqTNFPL.jpg',
    brand: 'Insta360',
    stock: 35,
    rating: 4.7
  },
  {
    id: '34',
    _id: '34',
    name: 'Garmin Fenix 7 Pro',
    description: 'Solar powered multisport watch.',
    price: 799,
    category: 'fitness',
    image: 'https://m.media-amazon.com/images/I/71yjOArb3YL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Garmin',
    stock: 22,
    rating: 4.9
  },
  {
    id: '35',
    _id: '35',
    name: 'JBL Charge 5',
    description: 'Portable waterproof speaker.',
    price: 179,
    category: 'audio',
    image: 'https://microless.com/cdn/products/a225db9116f168e7c9f250bcd7bda4de-hi.jpg',
    brand: 'JBL',
    stock: 140,
    rating: 4.7
  },
  {
    id: '36',
    _id: '36',
    name: 'Marshall Stanmore III',
    description: 'Classic home Bluetooth speaker.',
    price: 379,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/41SCO-fEVzL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Marshall',
    stock: 45,
    rating: 4.8
  },
  {
    id: '37',
    _id: '37',
    name: 'Elgato Stream Deck MK.2',
    description: '15 customizable LCD keys.',
    price: 149,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/5166khyKBGL.jpg',
    brand: 'Elgato',
    stock: 85,
    rating: 4.9
  },
  {
    id: '38',
    _id: '38',
    name: 'Blue Yeti USB Microphone',
    description: 'Professional recording mic.',
    price: 129,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/61rGxyu5lUL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Blue',
    stock: 115,
    rating: 4.8
  },
  {
    id: '39',
    _id: '39',
    name: 'iPad Pro 12.9" (M2)',
    description: 'Ultimate iPad experience.',
    price: 1099,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/81rxOSprYqL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Apple',
    stock: 55,
    rating: 4.9
  },
  {
    id: '40',
    _id: '40',
    name: 'Oculus Quest 3 (128GB)',
    description: 'Next-gen mixed reality.',
    price: 499,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61nkctF66PL.jpg',
    brand: 'Meta',
    stock: 70,
    rating: 4.7
  },
  {
    id: '41',
    _id: '41',
    name: 'NVIDIA GeForce RTX 4080',
    description: 'Ultimate gaming graphics card.',
    price: 1199,
    category: 'computers',
    image: 'https://rukmini1.flixcart.com/image/1500/1500/xif0q/graphics-card/2/f/v/geforce-rtx-4080-16gb-ventus-3x-oc-msi-original-imagt5y7ddpgg5pn.jpeg?q=70',
    brand: 'NVIDIA',
    stock: 5,
    rating: 4.9
  },
  {
    id: '42',
    _id: '42',
    name: 'Dell UltraSharp 27" 4K',
    description: 'Exceptional details and color.',
    price: 599,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/91tUHZCszIL.jpg',
    brand: 'Dell',
    stock: 35,
    rating: 4.8
  },
  {
    id: '43',
    _id: '43',
    name: 'Wacom Intuos Pro (Medium)',
    description: 'Creative pen tablet.',
    price: 349,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61HXRDydAQL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Wacom',
    stock: 28,
    rating: 4.7
  },
  {
    id: '44',
    _id: '44',
    name: 'Anker 737 Power Bank',
    description: '140W fast charging 24000mAh.',
    price: 149,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/71QrhaW+kAL.jpg',
    brand: 'Anker',
    stock: 190,
    rating: 4.9
  },
  {
    id: '45',
    _id: '45',
    name: 'Sennheiser Momentum 4',
    description: 'Audiophile-grade wireless sound.',
    price: 349,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/71zsm84mJsL.jpg',
    brand: 'Sennheiser',
    stock: 48,
    rating: 4.8
  },
  {
    id: '46',
    _id: '46',
    name: 'Wyze Cam Pan v3',
    description: 'Smart 360 security camera.',
    price: 49,
    category: 'smarthome',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSbdUF8MtQeiBahUn35ltA1Qm_VQ8E35pkLA&s',
    brand: 'Wyze',
    stock: 250,
    rating: 4.5
  },
  {
    id: '47',
    _id: '47',
    name: 'Oura Ring Gen3',
    description: 'Discreet health tracking ring.',
    price: 299,
    category: 'fitness',
    image: 'https://m.media-amazon.com/images/I/61pHtQLDz4L._UF350,350_QL80_.jpg',
    brand: 'Oura',
    stock: 35,
    rating: 4.7
  },
  {
    id: '48',
    _id: '48',
    name: 'Nanoleaf Shapes Triangles',
    description: 'Modular smart light panels.',
    price: 199,
    category: 'smarthome',
    image: 'https://m.media-amazon.com/images/I/71d+2pwGBpL._AC_UF894,1000_QL80_.jpg',
    brand: 'Nanoleaf',
    stock: 65,
    rating: 4.6
  },
  {
    id: '49',
    _id: '49',
    name: 'TP-Link Deco XE75 Mesh',
    description: 'AXE5400 Tri-Band WiFi 6E.',
    price: 399,
    category: 'smarthome',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqh1X6MouHkiAmkDwQRiIUobTvrY2BMXVukA&s',
    brand: 'TP-Link',
    stock: 95,
    rating: 4.8
  },
  {
    id: '50',
    _id: '50',
    name: 'SteelSeries Arctis Nova Pro',
    description: 'The absolute best gaming audio.',
    price: 349,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/61RMiMyIlGL._AC_UF1000,1000_QL80_.jpg',
    brand: 'SteelSeries',
    stock: 72,
    rating: 4.9
  },
  {
    id: '51',
    _id: '51',
    name: 'Alienware 34 Curved QD-OLED',
    description: 'First QD-OLED gaming monitor.',
    price: 999,
    category: 'computers',
    image: 'https://www.theitdepot.com/image/cache/catalog/products/images/proimages/39949-500-min-550x550.jpg',
    brand: 'Alienware',
    stock: 15,
    rating: 4.9
  },
  {
    id: '52',
    _id: '52',
    name: 'Razer Leviathan V2',
    description: 'Multi-driver PC gaming soundbar.',
    price: 249,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/71W+erooYNL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Razer',
    stock: 44,
    rating: 4.6
  },
  {
    id: '53',
    _id: '53',
    name: 'Sony PlayStation 5 Console',
    description: 'Experience lightning-fast loading and deeper immersion.',
    price: 499,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61qM7CPPcrL.jpg',
    brand: 'Sony',
    stock: 15,
    rating: 4.9
  },
  {
    id: '54',
    _id: '54',
    name: 'Sony DualSense Edge Wireless Controller',
    description: 'Custom controls designed for high performance.',
    price: 199,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61wcZaT2vkL._AC_UF894,1000_QL80_.jpg',
    brand: 'Sony',
    stock: 30,
    rating: 4.8
  },
  {
    id: '55',
    _id: '55',
    name: 'Sony PlayStation VR2',
    description: 'Escape into worlds that feel truly real.',
    price: 549,
    category: 'electronics',
    image: 'https://gmedia.playstation.com/is/image/SIEPDC/PSVR2-thumbnail-01-en-22feb22?$facebook$',
    brand: 'Sony',
    stock: 10,
    rating: 4.7
  },
  {
    id: '56',
    _id: '56',
    name: 'Sony Pulse 3D Wireless Headset',
    description: 'Fine-tuned for 3D Audio on PS5 consoles.',
    price: 99,
    category: 'audio',
    image: 'https://m.media-amazon.com/images/I/41IfEf6+4CL.jpg',
    brand: 'Sony',
    stock: 45,
    rating: 4.8
  },
  {
    id: '57',
    _id: '57',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Welcome to the era of mobile AI.',
    price: 1299,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/717Q2swzhBL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Samsung',
    stock: 25,
    rating: 4.9
  },
  {
    id: '58',
    _id: '58',
    name: 'Google Pixel 8',
    description: 'The all-new phone engineered by Google.',
    price: 699,
    category: 'electronics',
    image: 'https://www.designinfo.in/wp-content/uploads/2024/11/Google-Pixel-8-5G-8GB-RAM-256GB-Hazel-Imported-1.webp',
    brand: 'Google',
    stock: 20,
    rating: 4.7
  },
  {
    id: '59',
    _id: '59',
    name: 'OnePlus 12 (Emerald Green)',
    description: 'Smooth Beyond Belief performance.',
    price: 799,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/717Qo4MH97L._AC_UF1000,1000_QL80_.jpg',
    brand: 'OnePlus',
    stock: 35,
    rating: 4.8
  },
  {
    id: '60',
    _id: '60',
    name: 'Nothing Phone (2) Dark Edition',
    description: 'A new era for the smartphone.',
    price: 599,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61cZJcKweLL._AC_UF1000,1000_QL80_.jpg',
    brand: 'Nothing',
    stock: 50,
    rating: 4.7
  }
];
